import Image from 'next/image'
import About from './components/About'
import Contact from './components/Contact'
import Main from './components/Main'
import Navbar from './components/Navbar'
import Skills from './components/Skills'
import Projects from './components/Projects'

export default function Home() {
  return (
  <div>
    <head>
      <title>Hanniya Aijaz | Resume</title>
      <meta name="description" content="Generated by Hanniya Siddiqui" />
      <link rel="icon" href="/favicon.ico" />

    </head>

    <Navbar/>
    <Main/>
    <About/>
    <Skills />
    <Projects />
    <Contact/>
  </div>
  )
}
